kind: pipeline
type: docker
name: deploy

steps:
  - name: Build da Imagem Docker
    image: docker:latest
    commands:
      - docker build -t teste_deploy:latest .

  #- name: Redeploy
  #  image: docker:latest
  #  commands:
  #    - docker service update --force --image fabrica:latest app_fabrica

  - name: Subir Serviço no Docker Swarm
    image: docker:latest
    commands:
      - docker service rm app_teste_deploy || true
      - docker stack deploy -c Docker-compose.yml app
