version: '3.8'

services:
  teste_deploy:
    # No Docker Swarm, a imagem já deve estar construída (o seu .drone.yml já faz o build com esta tag)
    image: teste_deploy:latest
    ports:
      - "80:80"
    deploy:
      mode: global