version: '3.8'

services:
  teste_deploy:
    # No Docker Swarm, a imagem já deve estar construída (o seu .drone.yml já faz o build com esta tag)
    image: teste_deploy:latest
    ports:
      - "80:80"
    deploy:
      mode: replicated
      # Quantas instâncias você quer rodando em paralelo
      replicas: 3 
      placement:
        constraints:
          # Define em quais nós (servidores) os containers podem rodar.
          # Você pode usar:
          # - node.role == worker  (Roda apenas nos workers)
          # - node.role == manager (Roda apenas nos managers)
          - node.role == worker