version: '3.8'

services:
  teste_deploy:
    # A imagem agora aponta para o seu registry privado, 
    # permitindo que os workers consigam baixá-la via rede!
    image: repositorio-imagem.akrbrands.com.br/teste_deploy:latest
    ports:
      - "80:80"
    deploy:
      mode: global